# wrangler.toml
name = 'comment'
main = "src/comet.ts"
compatibility_date = "2025-06-14"

[[d1_databases]]
binding = "DB"
database_name = "comet-db"
database_id = "local" # ローカル開発時は wrangler d1 create <DB_NAME> --local で作成した際のIDを指定することが多いです

[vars]
ADMIN_PASS = "test"

[assets]
directory = "./public"